### ISSUE TITLE
dvswitch.org offline

### ISSUE THREAD

**Issue by 9V1LH** [phdlee/dvpi#7]
dvswitch.org seems to be offline. Please update the installation procedure. E.g. get the sources from github and compile them.

**Comment by waheiko** [comment]
Dvswitch.org is not offline. IT didnt work with hamnet. I had the same Problem. With normal Internet it works. 73 DO3HW

**Comment by 9V1LH** [comment]
> 
> 
> Dvswitch.org is not offline. IT didnt work with hamnet. I had the same Problem. With normal Internet it works. 73 DO3HW

Thanks Heiko. I already forgot that my network is always connected to the Hamnet ;)
